title: Emanon_2100's Homepage
page-top-title: Emanon_2100
top-section-bg-text: Be what you wanna be
home-subtitle: Emanon_2100&ensp;|&ensp;Alfred
copyright-text: '&copy; Emanon_2100 2023-2025. All Rights Reserved.'
